services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    ports:
      - "50051:50051"

  biometric-service:
    ports:
      - "50052:50052"

  training-service:
    ports:
      - "50053:50053"

  gateway:
    ports:
      - "8080:8080"

  ml-classifier:
    ports:
      - "8001:8001"

  ml-generator:
    ports:
      - "8002:8002"