# Trivy misconfiguration ignore rules
# https://aquasecurity.github.io/trivy/latest/docs/config/filtering/#by-exceptions-using-trivyignoreyaml
- rule: KSV-0014
  paths:
    - configs/k8s/deployments/postgres.yaml
  statement: PostgreSQL needs writable filesystem for data files

- rule: KSV-0014
  paths:
    - configs/k8s/deployments/rabbitmq.yaml
  statement: RabbitMQ needs writable filesystem for queue data
