sonar.projectKey=fitness-platform
sonar.projectName=FitPulse Platform
sonar.organization=mamuer

sonar.sources=cmd,internal,api,web/src
sonar.tests=cmd,internal,web/src
sonar.test.inclusions=**/*_test.go,**/*.test.jsx,**/*.test.js

sonar.exclusions=api/gen/**,web/dist/**,web/node_modules/**,mocks/**,**/*_test.go,**/*.test.jsx,**/*.test.js,**/swagger.yaml,**/openapi.yaml,**/*.proto,**/*.pb.go,configs/k8s/base/local-path-provisioner.yaml,configs/monitoring/node-exporter/daemonset.yaml
sonar.coverage.exclusions=api/gen/**,web/dist/**,web/node_modules/**,mocks/**,cmd/ml-classifier/**,cmd/device-emulator/**,**/swagger.yaml,**/openapi.yaml,**/*.proto,**/*.pb.go,cmd/ml_generator/main.py,cmd/**/main.go,web/src/main.jsx,web/src/App.jsx,web/src/index.css,web/src/test/setup.js

sonar.go.coverage.reportPaths=coverage/coverage.out
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.qualitygate.wait=true

sonar.python.version=3.14

sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12
sonar.issue.ignore.multicriteria.e1.ruleKey=kubernetes:S6431
sonar.issue.ignore.multicriteria.e1.resourceKey=configs/monitoring/node-exporter/daemonset.yaml
sonar.issue.ignore.multicriteria.e2.ruleKey=kubernetes:S6897
sonar.issue.ignore.multicriteria.e2.resourceKey=configs/monitoring/node-exporter/daemonset.yaml
sonar.issue.ignore.multicriteria.e3.ruleKey=kubernetes:S5849
sonar.issue.ignore.multicriteria.e3.resourceKey=configs/k8s/base/local-path-provisioner.yaml
sonar.issue.ignore.multicriteria.e4.ruleKey=kubernetes:S6431
sonar.issue.ignore.multicriteria.e4.resourceKey=configs/k8s/base/ingress-nginx/deployment.yaml
sonar.issue.ignore.multicriteria.e5.ruleKey=docker:S6506
sonar.issue.ignore.multicriteria.e5.resourceKey=configs/k8s/base/jobs/Dockerfile
sonar.issue.ignore.multicriteria.e6.ruleKey=plsql:VarcharUsageCheck
sonar.issue.ignore.multicriteria.e6.resourceKey=db/migrations/V1__full_schema.sql
sonar.issue.ignore.multicriteria.e7.ruleKey=plsql:SelectStarCheck
sonar.issue.ignore.multicriteria.e7.resourceKey=db/migrations/V1__full_schema.sql
sonar.issue.ignore.multicriteria.e8.ruleKey=plsql:BooleanLiteralComparisonCheck
sonar.issue.ignore.multicriteria.e8.resourceKey=db/migrations/V1__full_schema.sql
sonar.issue.ignore.multicriteria.e9.ruleKey=plsql:DeadCodeCheck
sonar.issue.ignore.multicriteria.e9.resourceKey=db/migrations/V1__full_schema.sql
sonar.issue.ignore.multicriteria.e10.ruleKey=plsql:S1192
sonar.issue.ignore.multicriteria.e10.resourceKey=db/migrations/V2__add_source_to_biometric_metrics.sql
sonar.issue.ignore.multicriteria.e11.ruleKey=go:S2077
sonar.issue.ignore.multicriteria.e11.resourceKey=internal/repository/postgres/pgsodium_user_repository.go
sonar.issue.ignore.multicriteria.e12.ruleKey=go:S1192
sonar.issue.ignore.multicriteria.e12.resourceKey=internal/repository/postgres/pgsodium_user_repository.go
