apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fitness-platform
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "fitness"
  DB_SSLMODE: "disable"
  REDIS_ADDR: "redis-service:6379"
  REDIS_DB: "0"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672/"
  USER_SERVICE_PORT: "50051"
  BIOMETRIC_SERVICE_PORT: "50052"
  TRAINING_SERVICE_PORT: "50053"
  GATEWAY_PORT: "8080"
  ML_CLASSIFIER_PORT: "8001"
  ML_GENERATOR_PORT: "8002"
  CACHE_TTL_SECONDS: "120"
  CACHE_TTL_JITTER_SECONDS: "30"