apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fitness-platform
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  JWT_SECRET: "my-super-secret-key-change-in-production-2024"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASS: "guest"