# scripts/run-local.ps1
# Fitness Platform - Local Startup Script for Windows
#
# Requires:
#   - Docker Desktop running
#   - .env file in project root (generated by generate-env.ps1)
#
# ALL services run in Docker. No local go run.

$ErrorActionPreference = "Stop"

# Fix: PowerShell 7 may not have Docker in PATH
$dockerPath = "C:\Program Files\Docker\Docker\resources\bin"
if (-not ($env:PATH -split ";" | Where-Object { $_ -eq $dockerPath })) {
    $env:PATH = "$dockerPath;$env:PATH"
}

# Fix: Ignore self-signed SSL certificate warnings for local dev
if ($PSVersionTable.PSVersion.Major -ge 7) {
    # PowerShell 7: use -SkipCertificateCheck in Invoke-WebRequest
    $PSDefaultParameterValues['Invoke-WebRequest:SkipCertificateCheck'] = $true
} else {
    [Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }
}

Write-Host "========================================"
Write-Host "   FITNESS PLATFORM - LOCAL STARTUP"
Write-Host "========================================"
Write-Host ""

# 1. Check Docker
Write-Host "[1/5] Checking Docker..."
docker ps --format "{{.Names}}" >$null 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "  ERROR - Docker is not running!" -ForegroundColor Red
    Write-Host "     Start Docker Desktop and try again." -ForegroundColor Yellow
    exit 1
}
Write-Host "  OK - Docker is running" -ForegroundColor Green

# 2. Create directories
Write-Host ""
Write-Host "[2/5] Creating directories..."
New-Item -ItemType Directory -Force -Path "logs" | Out-Null
New-Item -ItemType Directory -Force -Path "datasets/processed" | Out-Null
New-Item -ItemType Directory -Force -Path "models" | Out-Null
Write-Host "  OK - Directories created" -ForegroundColor Green

# 3. Check ML models
Write-Host ""
Write-Host "[3/5] Checking ML models..."
$hasModels = (Test-Path "models/classifier.keras") -and (Test-Path "models/generator.keras")
if ($hasModels) {
    Write-Host "  OK - ML models found" -ForegroundColor Green
} else {
    Write-Host "  WARNING - ML models not found" -ForegroundColor Yellow
    Write-Host "  Run: python cmd/ml-classifier/train.py" -ForegroundColor Gray
    Write-Host "       python cmd/ml-generator/train_gan.py" -ForegroundColor Gray
}

# 4. Load .env
Write-Host ""
Write-Host "[4/5] Loading environment from .env..."
$envFile = Join-Path $PSScriptRoot "..\.env"
if (-not (Test-Path $envFile)) {
    Write-Host "  ERROR - .env file not found!" -ForegroundColor Red
    Write-Host "  Generate it: scripts\generate-env.ps1" -ForegroundColor Yellow
    exit 1
}

$varCount = 0
Get-Content $envFile | Where-Object { $_ -match '^\s*([^#][^=]+)=(.*)$' } | ForEach-Object {
    $key = $Matches[1].Trim()
    $value = $Matches[2].Trim()
    if ($key -and $value) {
        [Environment]::SetEnvironmentVariable($key, $value, "Process")
        $varCount++
    }
}
Write-Host "  OK - $varCount variables loaded" -ForegroundColor Green

# 5. Start Docker containers
Write-Host ""
Write-Host "[5/5] Starting all services via Docker Compose..."
$composeFile = Join-Path $PSScriptRoot "..\deployments\docker-compose.yml"
docker compose --env-file $envFile -f $composeFile up -d
if ($LASTEXITCODE -ne 0) {
    Write-Host "  ERROR - docker compose failed!" -ForegroundColor Red
    Write-Host "  Check logs: docker compose -f $composeFile logs" -ForegroundColor Yellow
    exit 1
}

# Wait for services
Write-Host "  Waiting for services to initialize..." -ForegroundColor Gray
Start-Sleep -Seconds 20

# Health checks with retry
Write-Host ""
Write-Host "========================================"
Write-Host "   HEALTH CHECKS"
Write-Host "========================================"

$checks = @(
    @{Name="Gateway (HTTPS)"; URL="https://localhost:8443/health"}
)

foreach ($svc in $checks) {
    $ok = $false
    for ($i = 1; $i -le 3; $i++) {
        try {
            $uri = [System.Uri]$svc.URL
            $tcp = [System.Net.Sockets.TcpClient]::new()
            $tcp.Connect("localhost", $uri.Port)
            $tcp.Close()
            Write-Host "  [OK] $($svc.Name)" -ForegroundColor Green
            $ok = $true
            break
        } catch {
            Write-Host "  [RETRY $i/3] $($svc.Name)" -ForegroundColor Yellow
            Start-Sleep -Seconds 3
        }
    }
    if (-not $ok) {
        Write-Host "  [WARN] $($svc.Name) (Not responding)" -ForegroundColor Yellow
    }
}

# Summary
Write-Host ""
Write-Host "========================================"
Write-Host "   ALL SERVICES STARTED!"
Write-Host "========================================"
Write-Host "  HTTPS:         https://localhost:8443"
Write-Host "  API Docs:      https://localhost:8443/health"
Write-Host "  Gateway (dev): http://localhost:8085"
Write-Host "  ML Classifier: http://localhost:8001"
Write-Host "  ML Generator:  http://localhost:8002"
Write-Host "  RabbitMQ UI:   http://localhost:15672 (admin/guest)"
Write-Host "  PostgreSQL:    localhost:5432"
Write-Host "  Redis:         localhost:6379"
Write-Host ""
Write-Host "  Logs:          docker compose -f deployments/docker-compose.yml logs -f"
Write-Host "  Stop:          .\scripts\stop-local.bat"
Write-Host ""
Write-Host "Press Ctrl+C to stop all services..." -ForegroundColor Yellow

# Wait for interrupt
try {
    while ($true) { Start-Sleep -Seconds 1 }
} finally {
    Write-Host ""
    Write-Host "Stopping all services..." -ForegroundColor Yellow
    docker compose --env-file $envFile -f $composeFile down
    Write-Host "All services stopped." -ForegroundColor Green
}
