# RabbitMQ configuration file

# Default user
default_user = guest
default_pass = guest

# Listeners
listeners.tcp.default = 5672
management.tcp.port = 15672

# Memory limits
vm_memory_high_watermark.relative = 0.4

# Disk limits
disk_free_limit.absolute = 50MB

# Queues
queue_leader_locator = client-local

# Logging
log.console = true
log.console.level = info

# Channels
channel_max = 2047

# Connections
connection_max = 1024