events {
    worker_connections 1024;
}

http {
    server_tokens off;
    upstream tasks_cluster {
        server tasks_1:8082;
        server tasks_2:8082;
        server tasks_3:8082;
    }

    server {
        listen 8080;
        error_page 403 404 500 502 503 504 /errors/error.html;

        location /errors/ {
            root /usr/share/nginx/html;
            internal;
        }

        location /v1/tasks/ {
            proxy_pass http://tasks_cluster;
            proxy_set_header Authorization $http_authorization;
            add_header X-Upstream $upstream_addr;
        }
        location /health {
            proxy_pass http://tasks_cluster/health;
        }
    }
}