apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: healthfit-prod

configMapGenerator:
  - name: healthfit-config
    behavior: merge
    literals:
      - LOG_LEVEL=info

replicas:
  - name: healthfit-auth
    count: 3
  - name: healthfit-biometric-ingest
    count: 3