apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

namespace: healthfit-dev

configMapGenerator:
  - name: healthfit-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug