apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthfit-ml-classification
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: ml-classification
        env:
        - name: LOG_LEVEL
          value: "debug"