apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - hpa.yaml
  - open-wearables-ingress.yaml
images:
  - name: ghcr.io/mamuer/project/user-service
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/biometric-service
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/training-service
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/gateway
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/classifier
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/ml-generator
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/open-wearables-backend
    newTag: ${IMAGE_TAG:-latest}
  - name: ghcr.io/mamuer/project/open-wearables-frontend
    newTag: ${IMAGE_TAG:-latest}
